CFLAGS = -std=c++17 -O2
LDFLAGS = -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi

vulkan-test: main.cpp
	g++ $(CFLAGS) -o vulkan-test main.cpp $(LDFLAGS)

.PHONY: test clean

test: vulkan-test
	./vulkan-test

clean:
	rm -f vulkan-test